#!/bin/bash

user=$(logname)
desktop_path=$(eval echo ~$user/Desktop)

if [ -d "$desktop_path" ]; then
    cp /usr/share/applications/XFileTransit.desktop "$desktop_path/"
    chmod +x "$desktop_path/XFileTransit.desktop"
fi

exit 0

